import type { Metadata } from "next";
import "./globals.css";
import { HeaderDesktop } from "@/features";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-primary`}
      >
        <HeaderDesktop />
        <main className="container mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
